baseURL: http://example.org/
languageCode: en-us
title: Julia Furst Morgado
theme: PaperMod

params:
    ShowShareButtons: true
    TocOpen: true
    ShowCodeCopyButtons: true
    env: production
    profileMode:
        enabled: true
        title: "Hi, I'm Julia!" # optional default will be site title
        subtitle: "I'm a Cloud and DevOps advocate. My passion is making Cloud Native technologies and DevOps best practices easier to understand by sharing my knowledge and experiences. I'm also committed to empowering communities as the organizer of the *[NY Code & Coffee Meetup](https://www.newyorkcodeandcoffee.com/)*, AWS Community Builder, a *[Women Techmakers Ambassador](https://developers.google.com/womentechmakers)* and *[Girl Code Ambassador](https://www.girl-code.co.uk/girlcodeambassadors/julia-furst-morgado)*."
        imageUrl: "/img/julia2.jpeg" # optional
        imageWidth: 200 # custom size
        imageHeight: 200 # custom size
        buttons:
            - name: Blog
              url: "/posts"
            - name: Tags
              url: "/tags"

    socialIcons: # optional
    - name: twitter
      url: "https://twitter.com/juliafmorgado"
    - name: linkedin
      url: "https://www.linkedin.com/in/juliafmorgado"
    - name: github
      url: "https://github.com/juliafmorgado"
    - name: youtube
      url: "https://www.youtube.com/c/JuliaFMorgado"
    - name: instagram
      url: "https://www.instagram.com/juliafmorgado/"





#   homeInfoParams:
#     Title: "Hi, I'm Julia!"
#     Content: I'm a Cloud and DevOps advocate. My passion is making Cloud Native technologies and DevOps best practices easier to understand by sharing my knowledge and experiences. I'm also committed to empowering communities as the organizer of the NY Code & Coffee Meetup, AWS Community Builder, a Women Techmakers Ambassador and Girl Code Ambassador.

#   socialIcons:
#     - name: twitter
#       url: "https://twitter.com/juliafmorgado"
#     - name: linkedin
#       url: "https://www.linkedin.com/in/juliafmorgado"
#     - name: github
#       url: "https://github.com/juliafmorgado"
#     - name: youtube
#       url: "https://www.youtube.com/c/JuliaFMorgado"
#     - name: instagram
#       url: "https://www.instagram.com/juliafmorgado/"


#   cover:
#     ShowShareButtons: true

# menu:
#   main:
#   - identifier: about
#     name: About
#     url: /about/
#     weight: 10
#   - identifier: tags
#     name: Tags
#     url: /tags/
#     weight: 20